### ISSUE TITLE
Feature Request: Option to open in different container

### ISSUE THREAD

**Issue by EstherMoellman** [zncoder/confiner#1]
Hi,

First, thanks for your add-on. Very lightweight... nice.

If I well understood your add-on, the present behavior opens tabs in the same container. So tracking is not really minimized.

Please, I have a simple request: Add an option to automatically open every tab in a new different container (randomly). The TemporaryContainer add-on has this function, but for me this add-on becomes too big and full of functions (that I don't need). I prefer your add-on, a lightweight small add-on that just open every tab in a new different separate container. The less the better.

Thank you!

**Comment by zncoder** [comment]
The intention is open a site in its own container, not a random container. So we can confine a site to its own container for better privacy, but maintain the cookies associated with the site to avoid repeated login.

When you are visiting a website, if you click a link, the link is opened in the same tab with the same container. But if you open the link in a new tab (e.g. middle click), the link is opened in the container of the link.

**Comment by zncoder** [comment]
I planned to open a tab in a random ephemeral container. Probably I can add an option to open every tab in a random ephemeral container. Thanks,

**Comment by EstherMoellman** [comment]
@zncoder , thanks for your answer.

I'm personally interested in your second comment. It will be terrific if you go ahead with a kind of ephemeral container... in my own words: It will be the basic-version/fork of TemporaryContainers add-on. And this will be great for users (like me), that don't need fancy stuff, and that prefer simple lightweight add-ons, in this case: An add-on that automatically opens each/any tab in a kind of temporary container, just for the sick of privacy and nothing else, but without killing browser performance (RAM, CPU etc).

When the ephemeral container close (let's say 5 minutes after it), everything must be exterminated... everything!.... a complete sanitation of the container, cookies etc.

This will be a dream!

Thanks

PS: TemporaryContainers is great, but it started to be so complex and full of functions/options, that many add-ons conflict with TemporaryContainers. Firefox also doesn't help, because is full of bugs related to Containers, FPI First-Party-Isolation, Content blocking etc. So, we need a simple add-on to reduce conflicts while improving browser performance.

**Comment by zncoder** [comment]
Now it supports ephemeral containers and confined containers, and starts websites in ephemeral containers by default.

**Comment by EstherMoellman** [comment]
@zncoder , I'm starting to do my first tests on your new add-on, but at glance it seems F-A-N-T-A-S-T-I-C!... exactly what I wanted... THANK YOU!... and congrats for your outstanding work.

Please, just let me share with you my preliminary impressions:

1) I use DarkTheme (for both, FF' UI and webpages content), and the switching-icon of your add-on remains the same grey icon in both positions (permanent/ephemeral). Changing the color or the background of the icon will be enough (let's say blue for permanent, and grey for ephemeral). However, for those like me using DarkTheme, it will be amazing a simple "P"-icon for permanent, and "E"-icon for ephemeral.

2) Same logic applies to the container ID. I personally don't need the large container label appearing (it takes a lot of space). I confess you that I don't even understand the meaning of the glasses-icon. But a simple "P1" or "E1" will be spectacular (the simple 2 or maximum 3 digits container number, always in sequence, always reusing/recycling unused numbers etc... is much more informative than a large label + icon). For example, at TemporaryContainers add-on, I have a clean "CXXX", where "C" means container (I don't need "P" or "E" because all my containers are "E"), and "XXX" is the number: C1... C999. At your add-on, it might be P1... P999 or E1... E999. In my humble opinion, this is much more clean and informative than a large label that no one will remember. 

3) Simple question: When a permanent or ephemeral container is closed, everything inside is deleted/cleaned/sanitized? Or some info remains (besides history)?

4) You might be interested to know that your add-on gets well along with tab-group-add-ons ( for example https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/).
I tested and your add-on doesn't conflict with STG, tabs are always kept in their container (permanent/ephemeral).

After few more tests I still need to do from my side, I will give you my 5 stars at AMO' page, but you already gained my THANK YOU!... very, very, very nice add-on!

**Comment by EstherMoellman** [comment]
Hi again @zncoder ! I can't explain you how much I love your add-on. Thank you once again.

Please, if possible, answer the question #3 in my previous message:
"When a permanent or ephemeral container is closed, everything inside is deleted/cleaned/sanitized? Or some info remains (besides history)?"

I ask you because I did some tests, and:
a) Some containers never are deleted when the tab is closed.
b) Even having Firefox' preferences set to sanitize everything on exit, if there are tabs with containers, stuff remains when Firefox is reopened.

Also:
c) I can't make ephemeral container for www.google.com

Thank you in advance
